name: build

on: [push, pull_request]

env:
  LD_LIBRARY_PATH: /usr/local/lib64:/usr/local/lib/

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install -y libva-dev libdrm-dev ninja-build build-essential yasm nasm libva-drm2 meson

      - name: Install libva
        run: |
          git clone -b 2.14.0 --depth=1 https://github.com/intel/libva libva
          cd libva
          ./autogen.sh
          ./configure
          make
          sudo make install

      - name: Install onevpl
        run: |
          git clone -b v2022.1.5 https://github.com/oneapi-src/oneVPL onevpl
          cd onevpl
          mkdir build && cd build
          cmake -GNinja ..
          ninja
          sudo ninja install

      - name: Install onevpl-cpu
        run: |
          git clone -b v2022.1.5 https://github.com/oneapi-src/oneVPL-cpu onevpl-cpu
          cd onevpl-cpu
          source script/bootstrap
          script/build
          sudo script/install

      - name: Build examples
        run: |
          make

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install pylint flake8


      - name: Python syntax check
        run: |
          pylint *.py --errors-only --exit-zero
          flake8 *.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 *.py --count --exit-zero --statistics

      - name: Run encode example
        run: |
          ./hello_encode
          #python hello_encode.py TODO: Crashes on ModuleNotFoundError
